data "aws_caller_identity" "current" {}

# --- Secrets: the DB password is generated by Terraform and never leaves
# Secrets Manager except at boot, fetched by the instance's own IAM role
# (see modules/iam). It is never a Terraform variable, output, or anywhere
# in this repo's source — only a reference (the secret's ARN) is.
module "db_secret" {
  source = "./modules/secrets"
  name   = "three-tier-terraform/05/db-password"
}

# --- Artifacts bucket: force_destroy so `terraform destroy` removes it and
# its objects together — this bucket only ever holds build output, nothing
# that needs to outlive the lesson.
resource "aws_s3_bucket" "artifacts" {
  bucket        = "three-tier-terraform-05-artifacts-${data.aws_caller_identity.current.account_id}"
  force_destroy = true

  tags = { Lesson = "05-complete-infra-provisioning" }
}

# --- Build the frontend locally (Vite) — Terraform orchestrates the build,
# it doesn't compile JS itself. Re-runs on every apply (a lab convenience;
# a real pipeline would trigger this from a CI build step, not Terraform).
resource "null_resource" "frontend_build" {
  triggers = { always = timestamp() }

  provisioner "local-exec" {
    working_dir = "${path.module}/../frontend"
    command     = "npm ci && npm run build"
  }
}

data "archive_file" "frontend_zip" {
  depends_on  = [null_resource.frontend_build]
  type        = "zip"
  source_dir  = "${path.module}/../frontend/dist"
  output_path = "${path.module}/.build/frontend.zip"
}

data "archive_file" "backend_zip" {
  type        = "zip"
  source_dir  = "${path.module}/../backend"
  output_path = "${path.module}/.build/backend.zip"
  excludes    = ["node_modules", ".env"]
}

resource "aws_s3_object" "frontend" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "frontend.zip"
  source = data.archive_file.frontend_zip.output_path
  etag   = data.archive_file.frontend_zip.output_md5
}

resource "aws_s3_object" "backend" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "backend.zip"
  source = data.archive_file.backend_zip.output_path
  etag   = data.archive_file.backend_zip.output_md5
}

resource "aws_s3_object" "migration" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "migration.sql"
  source = "${path.module}/../database/migrations/001_create_search_history.sql"
  etag   = filemd5("${path.module}/../database/migrations/001_create_search_history.sql")
}

# --- IAM: this instance can read exactly one secret and GetObject from
# exactly this one bucket — nothing else in the account.
module "instance_role" {
  source      = "./modules/iam"
  name        = "three-tier-terraform-05-ec2"
  secret_arns = [module.db_secret.secret_arn]
  s3_read_arns = [
    "${aws_s3_bucket.artifacts.arn}/*",
  ]
  enable_ssm = true
}

resource "aws_security_group" "web" {
  name        = "three-tier-terraform-05-web-sg"
  description = "HTTP from anywhere; no inbound SSH - debugging via SSM only"

  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    description = "all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Lesson = "05-complete-infra-provisioning" }
}

module "app" {
  source = "./modules/ec2"

  name                 = "three-tier-terraform-05-app"
  instance_type        = var.instance_type
  security_group_ids   = [aws_security_group.web.id]
  iam_instance_profile = module.instance_role.instance_profile_name
  extra_tags           = { Lesson = "05-complete-infra-provisioning" }

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    aws_region       = var.aws_region
    db_secret_arn    = module.db_secret.secret_arn
    db_name          = var.db_name
    db_user          = var.db_user
    artifacts_bucket = aws_s3_bucket.artifacts.id
    frontend_key     = aws_s3_object.frontend.key
    backend_key      = aws_s3_object.backend.key
    migration_key    = aws_s3_object.migration.key
  })
}
