variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "ap-southeast-1"
}

variable "aws_profile" {
  description = "AWS CLI profile to authenticate with"
  type        = string
  default     = "ostad"
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.micro"
}

# Generated by Copilot from the prompt in step 2 of the README — see main.tf.
variable "my_ip_cidr" {
  description = "Your own public IP, as a /32 CIDR, allowed to SSH into the instance"
  type        = string
  # No default on purpose: every student's IP is different. Copilot correctly
  # left this un-defaulted rather than guessing — see README "what to check" list.
}
