data "aws_caller_identity" "current" {}

module "vpc" {
  source = "./modules/vpc"
  name   = "three-tier-terraform-11"
}

# --- The full chained SG set from lesson 07, wired into a real deployment
# for the first time: alb -> frontend -> backend -> db, plus the bastion
# group both frontend-sg and backend-sg now accept SSH from.
module "sg" {
  source      = "./modules/security-group"
  name_prefix = "three-tier-terraform-11"
  vpc_id      = module.vpc.vpc_id
  my_ip_cidr  = var.my_ip_cidr
}

# --- A real SSH key pair, generated by Terraform itself (not something a
# student creates by hand beforehand). The private key is written locally
# and gitignored (*.pem) — never committed, never in a Terraform output.
resource "tls_private_key" "bastion" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "bastion" {
  key_name   = "three-tier-terraform-11-bastion"
  public_key = tls_private_key.bastion.public_key_openssh
}

resource "local_file" "private_key" {
  filename        = "${path.module}/three-tier-terraform-11-bastion.pem"
  content         = tls_private_key.bastion.private_key_pem
  file_permission = "0600"
}

module "db_secret" {
  source = "./modules/secrets"
  name   = "three-tier-terraform/11/db-password"
}

module "rds" {
  source             = "./modules/rds"
  identifier         = "three-tier-terraform-11"
  subnet_ids         = module.vpc.private_db_subnet_ids
  security_group_ids = [module.sg.db_sg_id]
  db_name            = var.db_name
  db_user            = var.db_user
  db_password        = module.db_secret.password
}

resource "aws_s3_bucket" "artifacts" {
  bucket        = "three-tier-terraform-11-artifacts-${data.aws_caller_identity.current.account_id}"
  force_destroy = true
  tags          = { Lesson = "11-complete-production-deployment" }
}

resource "null_resource" "frontend_build" {
  triggers = { always = timestamp() }
  provisioner "local-exec" {
    working_dir = "${path.module}/../frontend"
    command     = "npm ci && npm run build"
  }
}

data "archive_file" "frontend_zip" {
  depends_on  = [null_resource.frontend_build]
  type        = "zip"
  source_dir  = "${path.module}/../frontend/dist"
  output_path = "${path.module}/.build/frontend.zip"
}

data "archive_file" "backend_zip" {
  type        = "zip"
  source_dir  = "${path.module}/../backend"
  output_path = "${path.module}/.build/backend.zip"
  excludes    = ["node_modules", ".env"]
}

resource "aws_s3_object" "frontend" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "frontend.zip"
  source = data.archive_file.frontend_zip.output_path
  etag   = data.archive_file.frontend_zip.output_md5
}

resource "aws_s3_object" "backend" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "backend.zip"
  source = data.archive_file.backend_zip.output_path
  etag   = data.archive_file.backend_zip.output_md5
}

resource "aws_s3_object" "migration" {
  bucket = aws_s3_bucket.artifacts.id
  key    = "migration.sql"
  source = "${path.module}/../database/migrations/001_create_search_history.sql"
  etag   = filemd5("${path.module}/../database/migrations/001_create_search_history.sql")
}

module "app_role" {
  source       = "./modules/iam"
  name         = "three-tier-terraform-11-ec2"
  secret_arns  = [module.db_secret.secret_arn]
  s3_read_arns = ["${aws_s3_bucket.artifacts.arn}/*"]
  enable_ssm   = true
}

# --- The bastion also gets SSM, deliberately — lesson 10's point is that
# SSH-via-bastion and SSM coexist, neither replaces the other.
module "bastion_role" {
  source     = "./modules/iam"
  name       = "three-tier-terraform-11-bastion"
  enable_ssm = true
}

module "bastion" {
  source = "./modules/ec2"

  name                 = "three-tier-terraform-11-bastion"
  instance_type        = var.bastion_instance_type
  subnet_id            = module.vpc.public_subnet_ids[0]
  security_group_ids   = [module.sg.bastion_sg_id]
  iam_instance_profile = module.bastion_role.instance_profile_name
  associate_public_ip  = true
  key_name             = aws_key_pair.bastion.key_name
  extra_tags           = { Lesson = "11-complete-production-deployment", Tier = "bastion" }
}

module "backend" {
  source = "./modules/ec2"

  name                 = "three-tier-terraform-11-backend"
  instance_type        = var.backend_instance_type
  subnet_id            = module.vpc.private_app_subnet_ids[0]
  security_group_ids   = [module.sg.backend_sg_id]
  iam_instance_profile = module.app_role.instance_profile_name
  associate_public_ip  = false
  key_name             = aws_key_pair.bastion.key_name
  extra_tags           = { Lesson = "11-complete-production-deployment", Tier = "backend" }

  user_data = templatefile("${path.module}/user_data_backend.sh.tpl", {
    aws_region       = var.aws_region
    db_secret_arn    = module.db_secret.secret_arn
    db_host          = module.rds.address
    db_name          = var.db_name
    db_user          = var.db_user
    artifacts_bucket = aws_s3_bucket.artifacts.id
    backend_key      = aws_s3_object.backend.key
    migration_key    = aws_s3_object.migration.key
  })
}

module "frontend" {
  source = "./modules/ec2"

  name                 = "three-tier-terraform-11-frontend"
  instance_type        = var.frontend_instance_type
  subnet_id            = module.vpc.private_app_subnet_ids[1]
  security_group_ids   = [module.sg.frontend_sg_id]
  iam_instance_profile = module.app_role.instance_profile_name
  associate_public_ip  = false
  key_name             = aws_key_pair.bastion.key_name
  extra_tags           = { Lesson = "11-complete-production-deployment", Tier = "frontend" }

  user_data = templatefile("${path.module}/user_data_frontend.sh.tpl", {
    aws_region         = var.aws_region
    artifacts_bucket   = aws_s3_bucket.artifacts.id
    frontend_key       = aws_s3_object.frontend.key
    backend_private_ip = module.backend.private_ip
  })
}

module "alb" {
  source             = "./modules/alb"
  name               = "three-tier-terraform-11"
  vpc_id             = module.vpc.vpc_id
  public_subnet_ids  = module.vpc.public_subnet_ids
  security_group_ids = [module.sg.alb_sg_id]
  target_instance_id = module.frontend.instance_id
  target_port        = 80
  health_check_path  = "/health"
}
